//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizzes.QuizzesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaltField;
        
        private System.DateTime CreatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((object.ReferenceEquals(this.SaltField, value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Quizzes.QuizzesService.ExamListResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Quizzes.QuizzesService.QuizzesResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Quizzes.QuizzesService.AnswerSheetResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Quizzes.QuizzesService.DoneAnswerSheetResult))]
    public partial class BasicResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageError {
            get {
                return this.MessageErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageErrorField, value) != true)) {
                    this.MessageErrorField = value;
                    this.RaisePropertyChanged("MessageError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamListResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExamListResult : Quizzes.QuizzesService.BasicResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Quizzes.QuizzesService.Exam[] ExamsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Quizzes.QuizzesService.Exam[] Exams {
            get {
                return this.ExamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamsField, value) != true)) {
                    this.ExamsField = value;
                    this.RaisePropertyChanged("Exams");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizzesResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QuizzesResult : Quizzes.QuizzesService.BasicResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Quizzes.QuizzesService.AnswerSheet AnswerSheetField;
        
        private long IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChooseAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChooseBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChooseCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChooseDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Quizzes.QuizzesService.AnswerSheet AnswerSheet {
            get {
                return this.AnswerSheetField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerSheetField, value) != true)) {
                    this.AnswerSheetField = value;
                    this.RaisePropertyChanged("AnswerSheet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ChooseA {
            get {
                return this.ChooseAField;
            }
            set {
                if ((object.ReferenceEquals(this.ChooseAField, value) != true)) {
                    this.ChooseAField = value;
                    this.RaisePropertyChanged("ChooseA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ChooseB {
            get {
                return this.ChooseBField;
            }
            set {
                if ((object.ReferenceEquals(this.ChooseBField, value) != true)) {
                    this.ChooseBField = value;
                    this.RaisePropertyChanged("ChooseB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ChooseC {
            get {
                return this.ChooseCField;
            }
            set {
                if ((object.ReferenceEquals(this.ChooseCField, value) != true)) {
                    this.ChooseCField = value;
                    this.RaisePropertyChanged("ChooseC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ChooseD {
            get {
                return this.ChooseDField;
            }
            set {
                if ((object.ReferenceEquals(this.ChooseDField, value) != true)) {
                    this.ChooseDField = value;
                    this.RaisePropertyChanged("ChooseD");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerSheetResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AnswerSheetResult : Quizzes.QuizzesService.BasicResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Quizzes.QuizzesService.AnswerSheet AnswerSheetField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Quizzes.QuizzesService.AnswerSheet AnswerSheet {
            get {
                return this.AnswerSheetField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerSheetField, value) != true)) {
                    this.AnswerSheetField = value;
                    this.RaisePropertyChanged("AnswerSheet");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoneAnswerSheetResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DoneAnswerSheetResult : Quizzes.QuizzesService.BasicResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Quizzes.QuizzesService.AnswerSheet AnswerSheetField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Quizzes.QuizzesService.AnswerSheet AnswerSheet {
            get {
                return this.AnswerSheetField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerSheetField, value) != true)) {
                    this.AnswerSheetField = value;
                    this.RaisePropertyChanged("AnswerSheet");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exam", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Exam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        private double TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuizzesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Quizzes {
            get {
                return this.QuizzesField;
            }
            set {
                if ((object.ReferenceEquals(this.QuizzesField, value) != true)) {
                    this.QuizzesField = value;
                    this.RaisePropertyChanged("Quizzes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerSheet", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AnswerSheet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        private long UserIdField;
        
        private long ExamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private System.Nullable<double> ScoreField;
        
        private System.Nullable<long> CurrentQuizzesField;
        
        private bool IsClosedField;
        
        private System.DateTime CreatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long ExamId {
            get {
                return this.ExamIdField;
            }
            set {
                if ((this.ExamIdField.Equals(value) != true)) {
                    this.ExamIdField = value;
                    this.RaisePropertyChanged("ExamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<double> Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<long> CurrentQuizzes {
            get {
                return this.CurrentQuizzesField;
            }
            set {
                if ((this.CurrentQuizzesField.Equals(value) != true)) {
                    this.CurrentQuizzesField = value;
                    this.RaisePropertyChanged("CurrentQuizzes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool IsClosed {
            get {
                return this.IsClosedField;
            }
            set {
                if ((this.IsClosedField.Equals(value) != true)) {
                    this.IsClosedField = value;
                    this.RaisePropertyChanged("IsClosed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuizzesService.QuizzesSoap")]
    public interface QuizzesSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        Quizzes.QuizzesService.RegisterResponse Register(Quizzes.QuizzesService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.RegisterResponse> RegisterAsync(Quizzes.QuizzesService.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Quizzes.QuizzesService.LoginResponse Login(Quizzes.QuizzesService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.LoginResponse> LoginAsync(Quizzes.QuizzesService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        Quizzes.QuizzesService.LogoutResponse Logout(Quizzes.QuizzesService.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.LogoutResponse> LogoutAsync(Quizzes.QuizzesService.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeExam", ReplyAction="*")]
        Quizzes.QuizzesService.MakeExamResponse MakeExam(Quizzes.QuizzesService.MakeExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeExam", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.MakeExamResponse> MakeExamAsync(Quizzes.QuizzesService.MakeExamRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExamList", ReplyAction="*")]
        Quizzes.QuizzesService.GetExamListResponse GetExamList(Quizzes.QuizzesService.GetExamListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExamList", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.GetExamListResponse> GetExamListAsync(Quizzes.QuizzesService.GetExamListRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NextQuizzes", ReplyAction="*")]
        Quizzes.QuizzesService.NextQuizzesResponse NextQuizzes(Quizzes.QuizzesService.NextQuizzesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NextQuizzes", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.NextQuizzesResponse> NextQuizzesAsync(Quizzes.QuizzesService.NextQuizzesRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeAnswerSheet", ReplyAction="*")]
        Quizzes.QuizzesService.MakeAnswerSheetResponse MakeAnswerSheet(Quizzes.QuizzesService.MakeAnswerSheetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeAnswerSheet", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.MakeAnswerSheetResponse> MakeAnswerSheetAsync(Quizzes.QuizzesService.MakeAnswerSheetRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Answer", ReplyAction="*")]
        Quizzes.QuizzesService.AnswerResponse Answer(Quizzes.QuizzesService.AnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Answer", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.AnswerResponse> AnswerAsync(Quizzes.QuizzesService.AnswerRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoneAnswerSheet", ReplyAction="*")]
        Quizzes.QuizzesService.DoneAnswerSheetResponse DoneAnswerSheet(Quizzes.QuizzesService.DoneAnswerSheetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoneAnswerSheet", ReplyAction="*")]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.DoneAnswerSheetResponse> DoneAnswerSheetAsync(Quizzes.QuizzesService.DoneAnswerSheetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(Quizzes.QuizzesService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.User user;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(Quizzes.QuizzesService.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(Quizzes.QuizzesService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.BasicResult RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(Quizzes.QuizzesService.BasicResult RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Quizzes.QuizzesService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Quizzes.QuizzesService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.BasicResult LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(Quizzes.QuizzesService.BasicResult LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(Quizzes.QuizzesService.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string sessionToken) {
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(Quizzes.QuizzesService.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogoutResponseBody {
        
        public LogoutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeExam", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.MakeExamRequestBody Body;
        
        public MakeExamRequest() {
        }
        
        public MakeExamRequest(Quizzes.QuizzesService.MakeExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Quizzes.QuizzesService.Exam exam;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int numberOf;
        
        public MakeExamRequestBody() {
        }
        
        public MakeExamRequestBody(string sessionToken, Quizzes.QuizzesService.Exam exam, int numberOf) {
            this.sessionToken = sessionToken;
            this.exam = exam;
            this.numberOf = numberOf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeExamResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.MakeExamResponseBody Body;
        
        public MakeExamResponse() {
        }
        
        public MakeExamResponse(Quizzes.QuizzesService.MakeExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.BasicResult MakeExamResult;
        
        public MakeExamResponseBody() {
        }
        
        public MakeExamResponseBody(Quizzes.QuizzesService.BasicResult MakeExamResult) {
            this.MakeExamResult = MakeExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExamListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExamList", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.GetExamListRequestBody Body;
        
        public GetExamListRequest() {
        }
        
        public GetExamListRequest(Quizzes.QuizzesService.GetExamListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExamListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        public GetExamListRequestBody() {
        }
        
        public GetExamListRequestBody(string sessionToken) {
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExamListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExamListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.GetExamListResponseBody Body;
        
        public GetExamListResponse() {
        }
        
        public GetExamListResponse(Quizzes.QuizzesService.GetExamListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExamListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.ExamListResult GetExamListResult;
        
        public GetExamListResponseBody() {
        }
        
        public GetExamListResponseBody(Quizzes.QuizzesService.ExamListResult GetExamListResult) {
            this.GetExamListResult = GetExamListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextQuizzesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextQuizzes", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.NextQuizzesRequestBody Body;
        
        public NextQuizzesRequest() {
        }
        
        public NextQuizzesRequest(Quizzes.QuizzesService.NextQuizzesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NextQuizzesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Quizzes.QuizzesService.AnswerSheet answerSheet;
        
        public NextQuizzesRequestBody() {
        }
        
        public NextQuizzesRequestBody(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            this.sessionToken = sessionToken;
            this.answerSheet = answerSheet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextQuizzesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextQuizzesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.NextQuizzesResponseBody Body;
        
        public NextQuizzesResponse() {
        }
        
        public NextQuizzesResponse(Quizzes.QuizzesService.NextQuizzesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NextQuizzesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.QuizzesResult NextQuizzesResult;
        
        public NextQuizzesResponseBody() {
        }
        
        public NextQuizzesResponseBody(Quizzes.QuizzesService.QuizzesResult NextQuizzesResult) {
            this.NextQuizzesResult = NextQuizzesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeAnswerSheetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeAnswerSheet", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.MakeAnswerSheetRequestBody Body;
        
        public MakeAnswerSheetRequest() {
        }
        
        public MakeAnswerSheetRequest(Quizzes.QuizzesService.MakeAnswerSheetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeAnswerSheetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Quizzes.QuizzesService.AnswerSheet answerSheet;
        
        public MakeAnswerSheetRequestBody() {
        }
        
        public MakeAnswerSheetRequestBody(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            this.sessionToken = sessionToken;
            this.answerSheet = answerSheet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeAnswerSheetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeAnswerSheetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.MakeAnswerSheetResponseBody Body;
        
        public MakeAnswerSheetResponse() {
        }
        
        public MakeAnswerSheetResponse(Quizzes.QuizzesService.MakeAnswerSheetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeAnswerSheetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.AnswerSheetResult MakeAnswerSheetResult;
        
        public MakeAnswerSheetResponseBody() {
        }
        
        public MakeAnswerSheetResponseBody(Quizzes.QuizzesService.AnswerSheetResult MakeAnswerSheetResult) {
            this.MakeAnswerSheetResult = MakeAnswerSheetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnswerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Answer", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.AnswerRequestBody Body;
        
        public AnswerRequest() {
        }
        
        public AnswerRequest(Quizzes.QuizzesService.AnswerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Quizzes.QuizzesService.AnswerSheet answerSheet;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long quizzesId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string answer;
        
        public AnswerRequestBody() {
        }
        
        public AnswerRequestBody(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet, long quizzesId, string answer) {
            this.sessionToken = sessionToken;
            this.answerSheet = answerSheet;
            this.quizzesId = quizzesId;
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnswerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnswerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.AnswerResponseBody Body;
        
        public AnswerResponse() {
        }
        
        public AnswerResponse(Quizzes.QuizzesService.AnswerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.BasicResult AnswerResult;
        
        public AnswerResponseBody() {
        }
        
        public AnswerResponseBody(Quizzes.QuizzesService.BasicResult AnswerResult) {
            this.AnswerResult = AnswerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoneAnswerSheetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoneAnswerSheet", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.DoneAnswerSheetRequestBody Body;
        
        public DoneAnswerSheetRequest() {
        }
        
        public DoneAnswerSheetRequest(Quizzes.QuizzesService.DoneAnswerSheetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoneAnswerSheetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Quizzes.QuizzesService.AnswerSheet answerSheet;
        
        public DoneAnswerSheetRequestBody() {
        }
        
        public DoneAnswerSheetRequestBody(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            this.sessionToken = sessionToken;
            this.answerSheet = answerSheet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoneAnswerSheetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoneAnswerSheetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Quizzes.QuizzesService.DoneAnswerSheetResponseBody Body;
        
        public DoneAnswerSheetResponse() {
        }
        
        public DoneAnswerSheetResponse(Quizzes.QuizzesService.DoneAnswerSheetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoneAnswerSheetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Quizzes.QuizzesService.DoneAnswerSheetResult DoneAnswerSheetResult;
        
        public DoneAnswerSheetResponseBody() {
        }
        
        public DoneAnswerSheetResponseBody(Quizzes.QuizzesService.DoneAnswerSheetResult DoneAnswerSheetResult) {
            this.DoneAnswerSheetResult = DoneAnswerSheetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuizzesSoapChannel : Quizzes.QuizzesService.QuizzesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuizzesSoapClient : System.ServiceModel.ClientBase<Quizzes.QuizzesService.QuizzesSoap>, Quizzes.QuizzesService.QuizzesSoap {
        
        public QuizzesSoapClient() {
        }
        
        public QuizzesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuizzesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuizzesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuizzesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.RegisterResponse Quizzes.QuizzesService.QuizzesSoap.Register(Quizzes.QuizzesService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public Quizzes.QuizzesService.BasicResult Register(Quizzes.QuizzesService.User user) {
            Quizzes.QuizzesService.RegisterRequest inValue = new Quizzes.QuizzesService.RegisterRequest();
            inValue.Body = new Quizzes.QuizzesService.RegisterRequestBody();
            inValue.Body.user = user;
            Quizzes.QuizzesService.RegisterResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.RegisterResponse> Quizzes.QuizzesService.QuizzesSoap.RegisterAsync(Quizzes.QuizzesService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.RegisterResponse> RegisterAsync(Quizzes.QuizzesService.User user) {
            Quizzes.QuizzesService.RegisterRequest inValue = new Quizzes.QuizzesService.RegisterRequest();
            inValue.Body = new Quizzes.QuizzesService.RegisterRequestBody();
            inValue.Body.user = user;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.LoginResponse Quizzes.QuizzesService.QuizzesSoap.Login(Quizzes.QuizzesService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public Quizzes.QuizzesService.BasicResult Login(string username, string password) {
            Quizzes.QuizzesService.LoginRequest inValue = new Quizzes.QuizzesService.LoginRequest();
            inValue.Body = new Quizzes.QuizzesService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Quizzes.QuizzesService.LoginResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.LoginResponse> Quizzes.QuizzesService.QuizzesSoap.LoginAsync(Quizzes.QuizzesService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.LoginResponse> LoginAsync(string username, string password) {
            Quizzes.QuizzesService.LoginRequest inValue = new Quizzes.QuizzesService.LoginRequest();
            inValue.Body = new Quizzes.QuizzesService.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.LogoutResponse Quizzes.QuizzesService.QuizzesSoap.Logout(Quizzes.QuizzesService.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public void Logout(string sessionToken) {
            Quizzes.QuizzesService.LogoutRequest inValue = new Quizzes.QuizzesService.LogoutRequest();
            inValue.Body = new Quizzes.QuizzesService.LogoutRequestBody();
            inValue.Body.sessionToken = sessionToken;
            Quizzes.QuizzesService.LogoutResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).Logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.LogoutResponse> Quizzes.QuizzesService.QuizzesSoap.LogoutAsync(Quizzes.QuizzesService.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.LogoutResponse> LogoutAsync(string sessionToken) {
            Quizzes.QuizzesService.LogoutRequest inValue = new Quizzes.QuizzesService.LogoutRequest();
            inValue.Body = new Quizzes.QuizzesService.LogoutRequestBody();
            inValue.Body.sessionToken = sessionToken;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.MakeExamResponse Quizzes.QuizzesService.QuizzesSoap.MakeExam(Quizzes.QuizzesService.MakeExamRequest request) {
            return base.Channel.MakeExam(request);
        }
        
        public Quizzes.QuizzesService.BasicResult MakeExam(string sessionToken, Quizzes.QuizzesService.Exam exam, int numberOf) {
            Quizzes.QuizzesService.MakeExamRequest inValue = new Quizzes.QuizzesService.MakeExamRequest();
            inValue.Body = new Quizzes.QuizzesService.MakeExamRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.exam = exam;
            inValue.Body.numberOf = numberOf;
            Quizzes.QuizzesService.MakeExamResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).MakeExam(inValue);
            return retVal.Body.MakeExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.MakeExamResponse> Quizzes.QuizzesService.QuizzesSoap.MakeExamAsync(Quizzes.QuizzesService.MakeExamRequest request) {
            return base.Channel.MakeExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.MakeExamResponse> MakeExamAsync(string sessionToken, Quizzes.QuizzesService.Exam exam, int numberOf) {
            Quizzes.QuizzesService.MakeExamRequest inValue = new Quizzes.QuizzesService.MakeExamRequest();
            inValue.Body = new Quizzes.QuizzesService.MakeExamRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.exam = exam;
            inValue.Body.numberOf = numberOf;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).MakeExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.GetExamListResponse Quizzes.QuizzesService.QuizzesSoap.GetExamList(Quizzes.QuizzesService.GetExamListRequest request) {
            return base.Channel.GetExamList(request);
        }
        
        public Quizzes.QuizzesService.ExamListResult GetExamList(string sessionToken) {
            Quizzes.QuizzesService.GetExamListRequest inValue = new Quizzes.QuizzesService.GetExamListRequest();
            inValue.Body = new Quizzes.QuizzesService.GetExamListRequestBody();
            inValue.Body.sessionToken = sessionToken;
            Quizzes.QuizzesService.GetExamListResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).GetExamList(inValue);
            return retVal.Body.GetExamListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.GetExamListResponse> Quizzes.QuizzesService.QuizzesSoap.GetExamListAsync(Quizzes.QuizzesService.GetExamListRequest request) {
            return base.Channel.GetExamListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.GetExamListResponse> GetExamListAsync(string sessionToken) {
            Quizzes.QuizzesService.GetExamListRequest inValue = new Quizzes.QuizzesService.GetExamListRequest();
            inValue.Body = new Quizzes.QuizzesService.GetExamListRequestBody();
            inValue.Body.sessionToken = sessionToken;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).GetExamListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.NextQuizzesResponse Quizzes.QuizzesService.QuizzesSoap.NextQuizzes(Quizzes.QuizzesService.NextQuizzesRequest request) {
            return base.Channel.NextQuizzes(request);
        }
        
        public Quizzes.QuizzesService.QuizzesResult NextQuizzes(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            Quizzes.QuizzesService.NextQuizzesRequest inValue = new Quizzes.QuizzesService.NextQuizzesRequest();
            inValue.Body = new Quizzes.QuizzesService.NextQuizzesRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.answerSheet = answerSheet;
            Quizzes.QuizzesService.NextQuizzesResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).NextQuizzes(inValue);
            return retVal.Body.NextQuizzesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.NextQuizzesResponse> Quizzes.QuizzesService.QuizzesSoap.NextQuizzesAsync(Quizzes.QuizzesService.NextQuizzesRequest request) {
            return base.Channel.NextQuizzesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.NextQuizzesResponse> NextQuizzesAsync(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            Quizzes.QuizzesService.NextQuizzesRequest inValue = new Quizzes.QuizzesService.NextQuizzesRequest();
            inValue.Body = new Quizzes.QuizzesService.NextQuizzesRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.answerSheet = answerSheet;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).NextQuizzesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.MakeAnswerSheetResponse Quizzes.QuizzesService.QuizzesSoap.MakeAnswerSheet(Quizzes.QuizzesService.MakeAnswerSheetRequest request) {
            return base.Channel.MakeAnswerSheet(request);
        }
        
        public Quizzes.QuizzesService.AnswerSheetResult MakeAnswerSheet(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            Quizzes.QuizzesService.MakeAnswerSheetRequest inValue = new Quizzes.QuizzesService.MakeAnswerSheetRequest();
            inValue.Body = new Quizzes.QuizzesService.MakeAnswerSheetRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.answerSheet = answerSheet;
            Quizzes.QuizzesService.MakeAnswerSheetResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).MakeAnswerSheet(inValue);
            return retVal.Body.MakeAnswerSheetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.MakeAnswerSheetResponse> Quizzes.QuizzesService.QuizzesSoap.MakeAnswerSheetAsync(Quizzes.QuizzesService.MakeAnswerSheetRequest request) {
            return base.Channel.MakeAnswerSheetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.MakeAnswerSheetResponse> MakeAnswerSheetAsync(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            Quizzes.QuizzesService.MakeAnswerSheetRequest inValue = new Quizzes.QuizzesService.MakeAnswerSheetRequest();
            inValue.Body = new Quizzes.QuizzesService.MakeAnswerSheetRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.answerSheet = answerSheet;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).MakeAnswerSheetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.AnswerResponse Quizzes.QuizzesService.QuizzesSoap.Answer(Quizzes.QuizzesService.AnswerRequest request) {
            return base.Channel.Answer(request);
        }
        
        public Quizzes.QuizzesService.BasicResult Answer(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet, long quizzesId, string answer1) {
            Quizzes.QuizzesService.AnswerRequest inValue = new Quizzes.QuizzesService.AnswerRequest();
            inValue.Body = new Quizzes.QuizzesService.AnswerRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.answerSheet = answerSheet;
            inValue.Body.quizzesId = quizzesId;
            inValue.Body.answer = answer1;
            Quizzes.QuizzesService.AnswerResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).Answer(inValue);
            return retVal.Body.AnswerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.AnswerResponse> Quizzes.QuizzesService.QuizzesSoap.AnswerAsync(Quizzes.QuizzesService.AnswerRequest request) {
            return base.Channel.AnswerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.AnswerResponse> AnswerAsync(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet, long quizzesId, string answer) {
            Quizzes.QuizzesService.AnswerRequest inValue = new Quizzes.QuizzesService.AnswerRequest();
            inValue.Body = new Quizzes.QuizzesService.AnswerRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.answerSheet = answerSheet;
            inValue.Body.quizzesId = quizzesId;
            inValue.Body.answer = answer;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).AnswerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quizzes.QuizzesService.DoneAnswerSheetResponse Quizzes.QuizzesService.QuizzesSoap.DoneAnswerSheet(Quizzes.QuizzesService.DoneAnswerSheetRequest request) {
            return base.Channel.DoneAnswerSheet(request);
        }
        
        public Quizzes.QuizzesService.DoneAnswerSheetResult DoneAnswerSheet(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            Quizzes.QuizzesService.DoneAnswerSheetRequest inValue = new Quizzes.QuizzesService.DoneAnswerSheetRequest();
            inValue.Body = new Quizzes.QuizzesService.DoneAnswerSheetRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.answerSheet = answerSheet;
            Quizzes.QuizzesService.DoneAnswerSheetResponse retVal = ((Quizzes.QuizzesService.QuizzesSoap)(this)).DoneAnswerSheet(inValue);
            return retVal.Body.DoneAnswerSheetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quizzes.QuizzesService.DoneAnswerSheetResponse> Quizzes.QuizzesService.QuizzesSoap.DoneAnswerSheetAsync(Quizzes.QuizzesService.DoneAnswerSheetRequest request) {
            return base.Channel.DoneAnswerSheetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quizzes.QuizzesService.DoneAnswerSheetResponse> DoneAnswerSheetAsync(string sessionToken, Quizzes.QuizzesService.AnswerSheet answerSheet) {
            Quizzes.QuizzesService.DoneAnswerSheetRequest inValue = new Quizzes.QuizzesService.DoneAnswerSheetRequest();
            inValue.Body = new Quizzes.QuizzesService.DoneAnswerSheetRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.answerSheet = answerSheet;
            return ((Quizzes.QuizzesService.QuizzesSoap)(this)).DoneAnswerSheetAsync(inValue);
        }
    }
}
