//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Banking {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaltField;
        
        private System.DateTime CreatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((object.ReferenceEquals(this.SaltField, value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(App.Banking.AccountsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(App.Banking.AccountResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(App.Banking.TransferResult))]
    public partial class LoginResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageError {
            get {
                return this.MessageErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageErrorField, value) != true)) {
                    this.MessageErrorField = value;
                    this.RaisePropertyChanged("MessageError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountsResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountsResult : App.Banking.LoginResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private App.Banking.UserAccount[] AccountsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public App.Banking.UserAccount[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountResult : App.Banking.LoginResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private App.Banking.UserAccount AccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public App.Banking.UserAccount Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TransferResult : App.Banking.LoginResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private App.Banking.Transaction TransactionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public App.Banking.Transaction Transaction {
            get {
                return this.TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionField, value) != true)) {
                    this.TransactionField = value;
                    this.RaisePropertyChanged("Transaction");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        private decimal BalancesField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private long UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Balances {
            get {
                return this.BalancesField;
            }
            set {
                if ((this.BalancesField.Equals(value) != true)) {
                    this.BalancesField = value;
                    this.RaisePropertyChanged("Balances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        private long UserIdField;
        
        private long UserSessionField;
        
        private long UserAccountField;
        
        private decimal AmountField;
        
        private bool IsApproveField;
        
        private System.Nullable<System.DateTime> ApproveAtField;
        
        private long ApproveByField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserSession {
            get {
                return this.UserSessionField;
            }
            set {
                if ((this.UserSessionField.Equals(value) != true)) {
                    this.UserSessionField = value;
                    this.RaisePropertyChanged("UserSession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long UserAccount {
            get {
                return this.UserAccountField;
            }
            set {
                if ((this.UserAccountField.Equals(value) != true)) {
                    this.UserAccountField = value;
                    this.RaisePropertyChanged("UserAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsApprove {
            get {
                return this.IsApproveField;
            }
            set {
                if ((this.IsApproveField.Equals(value) != true)) {
                    this.IsApproveField = value;
                    this.RaisePropertyChanged("IsApprove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> ApproveAt {
            get {
                return this.ApproveAtField;
            }
            set {
                if ((this.ApproveAtField.Equals(value) != true)) {
                    this.ApproveAtField = value;
                    this.RaisePropertyChanged("ApproveAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public long ApproveBy {
            get {
                return this.ApproveByField;
            }
            set {
                if ((this.ApproveByField.Equals(value) != true)) {
                    this.ApproveByField = value;
                    this.RaisePropertyChanged("ApproveBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Banking.AccountSoap")]
    public interface AccountSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        App.Banking.RegisterResponse Register(App.Banking.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Banking.RegisterResponse> RegisterAsync(App.Banking.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        App.Banking.LoginResponse Login(App.Banking.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Banking.LoginResponse> LoginAsync(App.Banking.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        App.Banking.LogoutResponse Logout(App.Banking.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Banking.LogoutResponse> LogoutAsync(App.Banking.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Accounts", ReplyAction="*")]
        App.Banking.AccountsResponse Accounts(App.Banking.AccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Accounts", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Banking.AccountsResponse> AccountsAsync(App.Banking.AccountsRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAccount", ReplyAction="*")]
        App.Banking.NewAccountResponse NewAccount(App.Banking.NewAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Banking.NewAccountResponse> NewAccountAsync(App.Banking.NewAccountRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccount", ReplyAction="*")]
        App.Banking.getAccountResponse getAccount(App.Banking.getAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Banking.getAccountResponse> getAccountAsync(App.Banking.getAccountRequest request);
        
        // CODEGEN: Generating message contract since element name sessionToken from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/transfer", ReplyAction="*")]
        App.Banking.transferResponse transfer(App.Banking.transferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/transfer", ReplyAction="*")]
        System.Threading.Tasks.Task<App.Banking.transferResponse> transferAsync(App.Banking.transferRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(App.Banking.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Banking.User user;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(App.Banking.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(App.Banking.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Banking.LoginResult RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(App.Banking.LoginResult RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(App.Banking.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(App.Banking.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Banking.LoginResult LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(App.Banking.LoginResult LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(App.Banking.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string sessionToken) {
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(App.Banking.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogoutResponseBody {
        
        public LogoutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Accounts", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.AccountsRequestBody Body;
        
        public AccountsRequest() {
        }
        
        public AccountsRequest(App.Banking.AccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        public AccountsRequestBody() {
        }
        
        public AccountsRequestBody(string sessionToken) {
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountsResponse", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.AccountsResponseBody Body;
        
        public AccountsResponse() {
        }
        
        public AccountsResponse(App.Banking.AccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Banking.AccountsResult AccountsResult;
        
        public AccountsResponseBody() {
        }
        
        public AccountsResponseBody(App.Banking.AccountsResult AccountsResult) {
            this.AccountsResult = AccountsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewAccount", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.NewAccountRequestBody Body;
        
        public NewAccountRequest() {
        }
        
        public NewAccountRequest(App.Banking.NewAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal balances;
        
        public NewAccountRequestBody() {
        }
        
        public NewAccountRequestBody(string sessionToken, decimal balances) {
            this.sessionToken = sessionToken;
            this.balances = balances;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.NewAccountResponseBody Body;
        
        public NewAccountResponse() {
        }
        
        public NewAccountResponse(App.Banking.NewAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Banking.AccountResult NewAccountResult;
        
        public NewAccountResponseBody() {
        }
        
        public NewAccountResponseBody(App.Banking.AccountResult NewAccountResult) {
            this.NewAccountResult = NewAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccount", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.getAccountRequestBody Body;
        
        public getAccountRequest() {
        }
        
        public getAccountRequest(App.Banking.getAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountNumber;
        
        public getAccountRequestBody() {
        }
        
        public getAccountRequestBody(string sessionToken, string accountNumber) {
            this.sessionToken = sessionToken;
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.getAccountResponseBody Body;
        
        public getAccountResponse() {
        }
        
        public getAccountResponse(App.Banking.getAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Banking.AccountResult getAccountResult;
        
        public getAccountResponseBody() {
        }
        
        public getAccountResponseBody(App.Banking.AccountResult getAccountResult) {
            this.getAccountResult = getAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="transfer", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.transferRequestBody Body;
        
        public transferRequest() {
        }
        
        public transferRequest(App.Banking.transferRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class transferRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string receiveAccountNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal amount;
        
        public transferRequestBody() {
        }
        
        public transferRequestBody(string sessionToken, string accountNumber, string receiveAccountNumber, decimal amount) {
            this.sessionToken = sessionToken;
            this.accountNumber = accountNumber;
            this.receiveAccountNumber = receiveAccountNumber;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="transferResponse", Namespace="http://tempuri.org/", Order=0)]
        public App.Banking.transferResponseBody Body;
        
        public transferResponse() {
        }
        
        public transferResponse(App.Banking.transferResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class transferResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public App.Banking.TransferResult transferResult;
        
        public transferResponseBody() {
        }
        
        public transferResponseBody(App.Banking.TransferResult transferResult) {
            this.transferResult = transferResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountSoapChannel : App.Banking.AccountSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountSoapClient : System.ServiceModel.ClientBase<App.Banking.AccountSoap>, App.Banking.AccountSoap {
        
        public AccountSoapClient() {
        }
        
        public AccountSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Banking.RegisterResponse App.Banking.AccountSoap.Register(App.Banking.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public App.Banking.LoginResult Register(App.Banking.User user) {
            App.Banking.RegisterRequest inValue = new App.Banking.RegisterRequest();
            inValue.Body = new App.Banking.RegisterRequestBody();
            inValue.Body.user = user;
            App.Banking.RegisterResponse retVal = ((App.Banking.AccountSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Banking.RegisterResponse> App.Banking.AccountSoap.RegisterAsync(App.Banking.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Banking.RegisterResponse> RegisterAsync(App.Banking.User user) {
            App.Banking.RegisterRequest inValue = new App.Banking.RegisterRequest();
            inValue.Body = new App.Banking.RegisterRequestBody();
            inValue.Body.user = user;
            return ((App.Banking.AccountSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Banking.LoginResponse App.Banking.AccountSoap.Login(App.Banking.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public App.Banking.LoginResult Login(string username, string password) {
            App.Banking.LoginRequest inValue = new App.Banking.LoginRequest();
            inValue.Body = new App.Banking.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            App.Banking.LoginResponse retVal = ((App.Banking.AccountSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Banking.LoginResponse> App.Banking.AccountSoap.LoginAsync(App.Banking.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Banking.LoginResponse> LoginAsync(string username, string password) {
            App.Banking.LoginRequest inValue = new App.Banking.LoginRequest();
            inValue.Body = new App.Banking.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((App.Banking.AccountSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Banking.LogoutResponse App.Banking.AccountSoap.Logout(App.Banking.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public void Logout(string sessionToken) {
            App.Banking.LogoutRequest inValue = new App.Banking.LogoutRequest();
            inValue.Body = new App.Banking.LogoutRequestBody();
            inValue.Body.sessionToken = sessionToken;
            App.Banking.LogoutResponse retVal = ((App.Banking.AccountSoap)(this)).Logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Banking.LogoutResponse> App.Banking.AccountSoap.LogoutAsync(App.Banking.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Banking.LogoutResponse> LogoutAsync(string sessionToken) {
            App.Banking.LogoutRequest inValue = new App.Banking.LogoutRequest();
            inValue.Body = new App.Banking.LogoutRequestBody();
            inValue.Body.sessionToken = sessionToken;
            return ((App.Banking.AccountSoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Banking.AccountsResponse App.Banking.AccountSoap.Accounts(App.Banking.AccountsRequest request) {
            return base.Channel.Accounts(request);
        }
        
        public App.Banking.AccountsResult Accounts(string sessionToken) {
            App.Banking.AccountsRequest inValue = new App.Banking.AccountsRequest();
            inValue.Body = new App.Banking.AccountsRequestBody();
            inValue.Body.sessionToken = sessionToken;
            App.Banking.AccountsResponse retVal = ((App.Banking.AccountSoap)(this)).Accounts(inValue);
            return retVal.Body.AccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Banking.AccountsResponse> App.Banking.AccountSoap.AccountsAsync(App.Banking.AccountsRequest request) {
            return base.Channel.AccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Banking.AccountsResponse> AccountsAsync(string sessionToken) {
            App.Banking.AccountsRequest inValue = new App.Banking.AccountsRequest();
            inValue.Body = new App.Banking.AccountsRequestBody();
            inValue.Body.sessionToken = sessionToken;
            return ((App.Banking.AccountSoap)(this)).AccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Banking.NewAccountResponse App.Banking.AccountSoap.NewAccount(App.Banking.NewAccountRequest request) {
            return base.Channel.NewAccount(request);
        }
        
        public App.Banking.AccountResult NewAccount(string sessionToken, decimal balances) {
            App.Banking.NewAccountRequest inValue = new App.Banking.NewAccountRequest();
            inValue.Body = new App.Banking.NewAccountRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.balances = balances;
            App.Banking.NewAccountResponse retVal = ((App.Banking.AccountSoap)(this)).NewAccount(inValue);
            return retVal.Body.NewAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Banking.NewAccountResponse> App.Banking.AccountSoap.NewAccountAsync(App.Banking.NewAccountRequest request) {
            return base.Channel.NewAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Banking.NewAccountResponse> NewAccountAsync(string sessionToken, decimal balances) {
            App.Banking.NewAccountRequest inValue = new App.Banking.NewAccountRequest();
            inValue.Body = new App.Banking.NewAccountRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.balances = balances;
            return ((App.Banking.AccountSoap)(this)).NewAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Banking.getAccountResponse App.Banking.AccountSoap.getAccount(App.Banking.getAccountRequest request) {
            return base.Channel.getAccount(request);
        }
        
        public App.Banking.AccountResult getAccount(string sessionToken, string accountNumber) {
            App.Banking.getAccountRequest inValue = new App.Banking.getAccountRequest();
            inValue.Body = new App.Banking.getAccountRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.accountNumber = accountNumber;
            App.Banking.getAccountResponse retVal = ((App.Banking.AccountSoap)(this)).getAccount(inValue);
            return retVal.Body.getAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Banking.getAccountResponse> App.Banking.AccountSoap.getAccountAsync(App.Banking.getAccountRequest request) {
            return base.Channel.getAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Banking.getAccountResponse> getAccountAsync(string sessionToken, string accountNumber) {
            App.Banking.getAccountRequest inValue = new App.Banking.getAccountRequest();
            inValue.Body = new App.Banking.getAccountRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.accountNumber = accountNumber;
            return ((App.Banking.AccountSoap)(this)).getAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.Banking.transferResponse App.Banking.AccountSoap.transfer(App.Banking.transferRequest request) {
            return base.Channel.transfer(request);
        }
        
        public App.Banking.TransferResult transfer(string sessionToken, string accountNumber, string receiveAccountNumber, decimal amount) {
            App.Banking.transferRequest inValue = new App.Banking.transferRequest();
            inValue.Body = new App.Banking.transferRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.accountNumber = accountNumber;
            inValue.Body.receiveAccountNumber = receiveAccountNumber;
            inValue.Body.amount = amount;
            App.Banking.transferResponse retVal = ((App.Banking.AccountSoap)(this)).transfer(inValue);
            return retVal.Body.transferResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.Banking.transferResponse> App.Banking.AccountSoap.transferAsync(App.Banking.transferRequest request) {
            return base.Channel.transferAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.Banking.transferResponse> transferAsync(string sessionToken, string accountNumber, string receiveAccountNumber, decimal amount) {
            App.Banking.transferRequest inValue = new App.Banking.transferRequest();
            inValue.Body = new App.Banking.transferRequestBody();
            inValue.Body.sessionToken = sessionToken;
            inValue.Body.accountNumber = accountNumber;
            inValue.Body.receiveAccountNumber = receiveAccountNumber;
            inValue.Body.amount = amount;
            return ((App.Banking.AccountSoap)(this)).transferAsync(inValue);
        }
    }
}
